#!/bin/bash

# set -ex
PATH=${PATH}:/var/vcap/packages/docker/bin/
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock

USERS=$(echo ${USER} | sed 's/[+!@#$%^&*()]/-/g')

container_name="${USERS}-dockersh"
if ! docker ps -a | grep "${container_name}" -q; then
    docker create -it -e "USER=${USER}" \
           <% p('env', {}).each do |k,v| %> \
           <%= "--env \"#{k}=#{v.dump.gsub('"', '')}\" \\" %>
           <% end %> \
            --name "${container_name}" <%= p('image') %> <%= p('command') %> \
            &> /dev/null
fi

docker start "${container_name}" &> /dev/null
docker exec -i --user "<%= p('user')%>" -t "${container_name}" <%= p('command') %>
