#!/bin/bash

PATH=${PATH}:/var/vcap/packages/docker/bin/
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock

USERS=$(echo ${USER} | sed 's/@/-/g')

container_name="${USERS}-dockersh"
if ! docker ps -a | grep "${container_name}" -q; then
    docker create -it --name "${container_name}" busybox /bin/ash &> /dev/null
fi

docker start "${container_name}" &> /dev/null
docker attach "${container_name}"
