#!/bin/bash

set -e

# pull docker image
PATH=${PATH}:/var/vcap/packages/docker/bin/
export DOCKER_HOST=unix:///var/vcap/sys/run/docker/docker.sock

image="<%= p('image') %>"

found_image=$(docker search ${image} | cut -d' ' -f1 | grep -e "${image}$" | wc -l)
if [ "${found_image}" == "1" ]; then
    docker pull ${image}
fi
