#!/bin/bash

if ! grep -e 'pam-exec-oauth2' /etc/pam.d/common-auth -q; then
    # prepend pam oauth to commend auth config
    sed -i "1s;^;auth sufficient pam_exec.so quiet expose_authtok /var/vcap/jobs/oauth/bin/pam-exec-oauth2.sh\n;" \
	/etc/pam.d/common-auth
fi

# libnss-ato does not inherits groups
if ! grep -e '^AllowGroups' /etc/ssh/sshd_config -q; then
    sed -i 's$AllowGroups$# AllowGroups$g' /etc/ssh/sshd_config
    service ssh restart
fi

# TODO install libnss-atojh




